#!/bin/sh

cd ..
export OMP_NUM_THREADS=8
export CUDA_VISIBLE_DEVICES=4,5,6,7
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64

mpirun --allow-run-as-root -np $1 Rscript x.r
#mpirun --allow-run-as-root -np $1 Rscript y.r
#mpirun --allow-run-as-root -np $1 Rscript iris.r


